// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDbs_G2vejJUW4U6yG1_Xe2xpLgA8TsOs',
    appId: '1:830739650048:web:5ad48ff912c7eecfeaaae5',
    messagingSenderId: '830739650048',
    projectId: 'entrepreneur-growth-guide',
    authDomain: 'entrepreneur-growth-guide.firebaseapp.com',
    storageBucket: 'entrepreneur-growth-guide.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjo58pvydhJHLLqOKc7z-1jBNI1kYZR6U',
    appId: '1:830739650048:android:6edc3a02e0c2ab31eaaae5',
    messagingSenderId: '830739650048',
    projectId: 'entrepreneur-growth-guide',
    storageBucket: 'entrepreneur-growth-guide.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKCw-O__nU1rdoxNlKrSgkPG6CxVBYTck',
    appId: '1:830739650048:ios:ec40bfc03fc67a43eaaae5',
    messagingSenderId: '830739650048',
    projectId: 'entrepreneur-growth-guide',
    storageBucket: 'entrepreneur-growth-guide.firebasestorage.app',
    iosBundleId: 'com.example.entrepreneurGrowthGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKCw-O__nU1rdoxNlKrSgkPG6CxVBYTck',
    appId: '1:830739650048:ios:ec40bfc03fc67a43eaaae5',
    messagingSenderId: '830739650048',
    projectId: 'entrepreneur-growth-guide',
    storageBucket: 'entrepreneur-growth-guide.firebasestorage.app',
    iosBundleId: 'com.example.entrepreneurGrowthGuide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDbs_G2vejJUW4U6yG1_Xe2xpLgA8TsOs',
    appId: '1:830739650048:web:a5bb962e483318f8eaaae5',
    messagingSenderId: '830739650048',
    projectId: 'entrepreneur-growth-guide',
    authDomain: 'entrepreneur-growth-guide.firebaseapp.com',
    storageBucket: 'entrepreneur-growth-guide.firebasestorage.app',
  );

}